import { Music2, ListMusic } from 'lucide-react';
import { requireChurch } from '@/lib/auth';
import { addSong, addSongToSet, createSet } from './actions';

export default async function Worship(){
 const {supabase,churchId}=await requireChurch();
 const [{data:songs},{data:sets},{data:setSongs}]=await Promise.all([
  supabase.from('songs').select('*').eq('church_id',churchId).eq('active',true).order('title'),
  supabase.from('worship_sets').select('*').eq('church_id',churchId).order('scheduled_at',{ascending:false}),
  supabase.from('worship_set_songs').select('set_id,position,transpose_to,songs(id,title,artist,key)').order('position')
 ]);
 return <><header className="topbar"><div className="title"><span className="eyebrow">Louvor</span><h1>Músicas e repertórios</h1><p>Biblioteca de músicas, cifras e repertórios para cultos e eventos.</p></div></header>
 <section className="module-kpis"><div className="module-stat"><Music2 size={19}/><div><strong>{songs?.length||0}</strong><span>Músicas</span></div></div><div className="module-stat"><ListMusic size={19}/><div><strong>{sets?.length||0}</strong><span>Repertórios</span></div></div></section>
 <section className="content-grid admin-grid"><div className="stack"><section className="card"><div className="section-head"><h2>Biblioteca</h2></div>{songs?.length?<div className="table-wrap"><table className="table"><thead><tr><th>Música</th><th>Artista</th><th>Tom</th><th>Link</th></tr></thead><tbody>{songs.map(s=><tr key={s.id}><td><strong>{s.title}</strong></td><td>{s.artist||'—'}</td><td>{s.key||'—'}</td><td>{s.link_url?<a className="table-link" href={s.link_url} target="_blank" rel="noreferrer">Abrir</a>:'—'}</td></tr>)}</tbody></table></div>:<div className="empty">Nenhuma música cadastrada.</div>}</section>
 <section className="card"><h2>Repertórios</h2>{sets?.length?sets.map(set=><article className="set-card" key={set.id}><div className="section-head"><div><strong>{set.title}</strong><span>{set.scheduled_at?new Date(set.scheduled_at).toLocaleString('pt-BR'):'Sem data'}</span></div></div><div className="set-list">{(setSongs||[]).filter((x:any)=>x.set_id===set.id).map((x:any)=><div className="mini-item" key={x.songs?.id}><strong>{x.position}. {x.songs?.title}</strong><span>{x.transpose_to?'Tom '+x.transpose_to:(x.songs?.key?'Tom '+x.songs.key:'')}</span></div>)}</div><form action={addSongToSet} className="inline-add"><input type="hidden" name="set_id" value={set.id}/><select name="song_id" required><option value="">Adicionar música</option>{songs?.map(s=><option value={s.id} key={s.id}>{s.title}</option>)}</select><input name="transpose_to" placeholder="Tom"/><button type="submit">Adicionar</button></form></article>):<div className="empty">Nenhum repertório.</div>}</section></div>
 <aside className="stack"><section className="card"><h2>Nova música</h2><form action={addSong} className="form"><div className="field"><label>Título</label><input name="title" required/></div><div className="form-row"><div className="field"><label>Artista</label><input name="artist"/></div><div className="field"><label>Tom</label><input name="key" placeholder="G"/></div></div><div className="field"><label>Letra</label><textarea name="lyrics" rows={5}/></div><div className="field"><label>Cifra</label><textarea name="chords" rows={4}/></div><div className="field"><label>Link</label><input name="link_url" type="url"/></div><button className="btn" type="submit">Cadastrar música</button></form></section>
 <section className="card"><h2>Novo repertório</h2><form action={createSet} className="form"><div className="field"><label>Nome</label><input name="title" placeholder="Culto de Domingo" required/></div><div className="field"><label>Data</label><input name="scheduled_at" type="datetime-local"/></div><div className="field"><label>Observações</label><textarea name="notes" rows={3}/></div><button className="btn secondary" type="submit">Criar repertório</button></form></section></aside></section></>;
}
