import { Gift, Heart } from 'lucide-react';
import { requireChurch } from '@/lib/auth';
import { createCampaign, registerDonation } from './actions';

export default async function Donations(){
 const {supabase,churchId,roleKey}=await requireChurch();const isStaff=roleKey!=='member';
 const [{data:campaigns},{data:donations}]=await Promise.all([supabase.from('donation_campaigns').select('*').eq('church_id',churchId).eq('active',true).order('created_at',{ascending:false}),isStaff?supabase.from('donations').select('id,amount,method,anonymous,status,occurred_at,donation_campaigns(title),church_members(full_name)').eq('church_id',churchId).order('occurred_at',{ascending:false}).limit(100):Promise.resolve({data:[] as any[]})]);
 const total=(donations||[]).reduce((a:any,x:any)=>a+Number(x.amount),0);
 return <><header className="topbar"><div className="title"><span className="eyebrow">Generosidade</span><h1>Ofertas e doações</h1><p>Campanhas, contribuições e registro de ofertas.</p></div></header>
 <section className="donation-campaigns">{campaigns?.length?campaigns.map(c=><article className="card campaign-card" key={c.id}><span className="metric-icon"><Heart size={18}/></span><span className="eyebrow">Campanha</span><h2>{c.title}</h2><p>{c.description||'Contribua com este propósito.'}</p>{c.goal_amount&&<strong>Meta: {Number(c.goal_amount).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</strong>}</article>):<div className="card empty">Nenhuma campanha ativa.</div>}</section>
 <section className="content-grid admin-grid"><div className="card"><span className="eyebrow">Contribuir</span><h2>Registrar contribuição</h2><form action={registerDonation} className="form"><div className="field"><label>Campanha</label><select name="campaign_id"><option value="">Oferta geral</option>{campaigns?.map(c=><option value={c.id} key={c.id}>{c.title}</option>)}</select></div><div className="field"><label>Valor</label><input name="amount" type="number" min="0.01" step="0.01" required/></div><div className="field"><label>Método</label><select name="method"><option value="pix">PIX</option><option value="cash">Dinheiro</option><option value="card">Cartão</option><option value="transfer">Transferência</option></select></div><label className="check-row"><input name="anonymous" type="checkbox"/> Contribuição anônima</label><button className="btn" type="submit"><Gift size={16}/> Registrar contribuição</button></form></div>
 {isStaff&&<aside className="stack"><section className="card"><span className="eyebrow">Total registrado</span><h2 className="big-money">{total.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</h2>{donations?.slice(0,8).map((d:any)=><div className="mini-item" key={d.id}><strong>{d.anonymous?'Anônimo':d.church_members?.full_name||'Contribuinte'} • {Number(d.amount).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</strong><span>{d.donation_campaigns?.title||'Oferta geral'} • {d.method}</span></div>)}</section><section className="card"><h2>Nova campanha</h2><form action={createCampaign} className="form"><div className="field"><label>Título</label><input name="title" required/></div><div className="field"><label>Descrição</label><textarea name="description" rows={3}/></div><div className="field"><label>Meta</label><input name="goal_amount" type="number" step="0.01"/></div><div className="form-row"><div className="field"><label>Início</label><input name="starts_at" type="datetime-local"/></div><div className="field"><label>Fim</label><input name="ends_at" type="datetime-local"/></div></div><button className="btn secondary" type="submit">Criar campanha</button></form></section></aside>}</section></>;
}
