import { requireChurch } from '@/lib/auth';
import { createSchedule, updateScheduleStatus } from './actions';

export default async function VolunteersPage({searchParams}:{searchParams:Promise<{error?:string}>}) {
  const qs=await searchParams; const {supabase,churchId}=await requireChurch();
  const [{data},{data:members},{data:ministries},{data:events}]=await Promise.all([
    supabase.from('volunteer_schedules').select('id,function_name,starts_at,status,church_members(full_name),ministries(name),events(title)').eq('church_id',churchId).order('starts_at').limit(100),
    supabase.from('church_members').select('id,full_name').eq('church_id',churchId).neq('status','inactive').order('full_name'),
    supabase.from('ministries').select('id,name').eq('church_id',churchId).eq('active',true).order('name'),
    supabase.from('events').select('id,title,starts_at').eq('church_id',churchId).gte('starts_at',new Date().toISOString()).order('starts_at').limit(50),
  ]);
  return <><header className="topbar"><div className="title"><span className="eyebrow">Equipes</span><h1>Voluntários e escalas</h1><p>Monte escalas, evite conflitos e acompanhe confirmações.</p></div></header>{qs.error&&<p className="alert">{qs.error}</p>}<section className="content-grid admin-grid"><div className="card">{data?.length?<div className="table-wrap"><table className="table"><thead><tr><th>Voluntário</th><th>Função</th><th>Ministério</th><th>Evento</th><th>Horário</th><th>Status</th></tr></thead><tbody>{data.map((row:any)=>{const action=updateScheduleStatus.bind(null,row.id);return <tr key={row.id}><td>{row.church_members?.full_name||'—'}</td><td>{row.function_name}</td><td>{row.ministries?.name||'—'}</td><td>{row.events?.title||'—'}</td><td>{new Date(row.starts_at).toLocaleString('pt-BR')}</td><td><form action={action} className="inline-form"><select name="status" defaultValue={row.status}><option value="pending">Pendente</option><option value="confirmed">Confirmada</option><option value="declined">Recusada</option><option value="replacement_requested">Substituição</option></select><button type="submit">Salvar</button></form></td></tr>})}</tbody></table></div>:<div className="empty">Nenhuma escala cadastrada ainda.</div>}</div><aside className="card sticky-card"><h2>Nova escala</h2><form action={createSchedule} className="form"><div className="field"><label>Evento</label><select name="event_id" required><option value="">Selecione</option>{events?.map(e=><option value={e.id} key={e.id}>{e.title} — {new Date(e.starts_at).toLocaleDateString('pt-BR')}</option>)}</select></div><div className="field"><label>Voluntário</label><select name="member_id" required><option value="">Selecione</option>{members?.map(m=><option value={m.id} key={m.id}>{m.full_name}</option>)}</select></div><div className="field"><label>Ministério</label><select name="ministry_id"><option value="">Sem ministério</option>{ministries?.map(m=><option value={m.id} key={m.id}>{m.name}</option>)}</select></div><div className="field"><label>Função</label><input name="function_name" placeholder="Recepção, vocal, câmera..." required/></div><button className="btn" type="submit">Criar escala</button></form></aside></section></>;
}
