import { UsersRound } from 'lucide-react';
import { requireChurch } from '@/lib/auth';
import { addYouthMember } from './actions';
export default async function Youth(){
 const {supabase,churchId}=await requireChurch();
 const {data:ministry}=await supabase.from('ministries').select('id').eq('church_id',churchId).eq('name','Jovens').maybeSingle();
 const [{data:members},{data:allMembers},{data:events}]=await Promise.all([ministry?supabase.from('ministry_members').select('member_id,role_name,church_members(full_name,phone,birth_date)').eq('ministry_id',ministry.id).eq('active',true):Promise.resolve({data:[] as any[]}),supabase.from('church_members').select('id,full_name').eq('church_id',churchId).neq('status','inactive').order('full_name'),supabase.from('events').select('id,title,starts_at,address').eq('church_id',churchId).ilike('category','%jov%').gte('starts_at',new Date().toISOString()).order('starts_at').limit(10)]);
 return <><header className="topbar"><div className="title"><span className="eyebrow">Jovens</span><h1>Ministério de Jovens</h1><p>Integrantes, liderança e próximos encontros.</p></div></header><section className="content-grid admin-grid"><div className="stack"><section className="card"><div className="section-head"><h2>Integrantes</h2><span className="badge">{members?.length||0} pessoas</span></div>{members?.length?<div className="table-wrap"><table className="table"><thead><tr><th>Nome</th><th>Função</th><th>Contato</th><th>Nascimento</th></tr></thead><tbody>{members.map((r:any)=><tr key={r.member_id}><td><strong>{r.church_members?.full_name}</strong></td><td>{r.role_name||'Jovem'}</td><td>{r.church_members?.phone||'—'}</td><td>{r.church_members?.birth_date?new Date(r.church_members.birth_date+'T12:00:00').toLocaleDateString('pt-BR'):'—'}</td></tr>)}</tbody></table></div>:<div className="empty">Nenhum jovem vinculado.</div>}</section><section className="card"><h2>Próximos encontros</h2>{events?.length?events.map(e=><div className="event-item" key={e.id}><span className="metric-icon"><UsersRound size={17}/></span><div><h3>{e.title}</h3><p>{new Date(e.starts_at).toLocaleString('pt-BR')}{e.address?' • '+e.address:''}</p></div></div>):<div className="empty compact">Cadastre eventos com categoria “Jovens”.</div>}</section></div><aside className="card sticky-card"><h2>Adicionar integrante</h2><form action={addYouthMember} className="form"><div className="field"><label>Membro</label><select name="member_id" required><option value="">Selecione</option>{allMembers?.map(m=><option value={m.id} key={m.id}>{m.full_name}</option>)}</select></div><div className="field"><label>Função</label><input name="role_name" placeholder="Jovem, líder, apoio..."/></div><button className="btn" type="submit">Adicionar</button></form></aside></section></>;
}
