import { Boxes } from 'lucide-react';
import { requireChurch } from '@/lib/auth';
import { createAsset } from './actions';
export default async function Assets(){
 const {supabase,churchId}=await requireChurch(); const {data}=await supabase.from('assets').select('*').eq('church_id',churchId).order('name');
 const total=(data||[]).reduce((a,x)=>a+Number(x.purchase_value||0),0);
 return <><header className="topbar"><div className="title"><span className="eyebrow">Patrimônio</span><h1>Bens da igreja</h1><p>Equipamentos, instrumentos, móveis e ativos por local e situação.</p></div></header><section className="module-kpis"><div className="module-stat"><Boxes size={19}/><div><strong>{data?.length||0}</strong><span>Itens cadastrados</span></div></div><div className="module-stat"><CircleValue value={total}/></div></section><section className="content-grid admin-grid"><div className="card">{data?.length?<div className="table-wrap"><table className="table"><thead><tr><th>Bem</th><th>Categoria</th><th>Local</th><th>Status</th><th>Valor</th></tr></thead><tbody>{data.map(x=><tr key={x.id}><td><strong>{x.name}</strong><small className="table-sub">{x.serial_number||''}</small></td><td>{x.category||'—'}</td><td>{x.location||'—'}</td><td><span className="badge">{x.status}</span></td><td>{x.purchase_value?Number(x.purchase_value).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}):'—'}</td></tr>)}</tbody></table></div>:<div className="empty">Nenhum patrimônio cadastrado.</div>}</div><aside className="card sticky-card"><h2>Novo bem</h2><form action={createAsset} className="form"><div className="field"><label>Nome</label><input name="name" required/></div><div className="field"><label>Categoria</label><input name="category"/></div><div className="field"><label>Nº série/tombo</label><input name="serial_number"/></div><div className="field"><label>Local</label><input name="location"/></div><div className="form-row"><div className="field"><label>Compra</label><input name="purchase_date" type="date"/></div><div className="field"><label>Valor</label><input name="purchase_value" type="number" step="0.01"/></div></div><div className="field"><label>Status</label><select name="status"><option value="active">Ativo</option><option value="maintenance">Manutenção</option><option value="retired">Baixado</option></select></div><div className="field"><label>Observações</label><textarea name="notes" rows={3}/></div><button className="btn" type="submit">Cadastrar patrimônio</button></form></aside></section></>;
}
function CircleValue({value}:{value:number}){return <><CircleDollarSign size={19}/><div><strong>{value.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}</strong><span>Valor registrado</span></div></>}
import { CircleDollarSign } from 'lucide-react';
