import Link from 'next/link';
import { UsersRound } from 'lucide-react';
import { requireChurch } from '@/lib/auth';
import { createCell } from './actions';

const days=['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado'];
export default async function Cells(){
 const {supabase,churchId}=await requireChurch(); const {data,error}=await supabase.from('cells').select('id,name,weekday,starts_at,capacity,active,address').eq('church_id',churchId).order('name');
 return <><header className="topbar"><div className="title"><span className="eyebrow">Comunidade</span><h1>Células</h1><p>Pequenos grupos, liderança, participantes e frequência.</p></div></header><section className="content-grid admin-grid"><div className="card">{error?<p className="alert">{error.message}</p>:data?.length?<div className="table-wrap"><table className="table"><thead><tr><th>Nome</th><th>Dia</th><th>Horário</th><th>Local</th><th>Capacidade</th><th>Status</th></tr></thead><tbody>{data.map(cell=><tr key={cell.id}><td><Link className="table-link" href={'/cells/'+cell.id}>{cell.name}</Link></td><td>{cell.weekday===null?'—':days[cell.weekday]}</td><td>{cell.starts_at||'—'}</td><td>{cell.address||'—'}</td><td>{cell.capacity??'—'}</td><td><span className="badge">{cell.active?'Ativa':'Inativa'}</span></td></tr>)}</tbody></table></div>:<div className="empty">Nenhuma célula cadastrada.</div>}</div><aside className="card sticky-card"><div className="section-head"><h2>Nova célula</h2><span className="metric-icon"><UsersRound size={18}/></span></div><form action={createCell} className="form"><div className="field"><label htmlFor="name">Nome</label><input id="name" name="name" required/></div><div className="field"><label htmlFor="weekday">Dia</label><select id="weekday" name="weekday">{days.map((d,i)=><option value={i} key={d}>{d}</option>)}</select></div><div className="field"><label htmlFor="startsAt">Horário</label><input id="startsAt" name="startsAt" type="time"/></div><div className="field"><label htmlFor="address">Local</label><input id="address" name="address"/></div><div className="field"><label htmlFor="capacity">Capacidade</label><input id="capacity" name="capacity" type="number" min="1"/></div><button className="btn" type="submit">Cadastrar célula</button></form></aside></section></>;
}
