import Link from 'next/link';
import { CalendarDays, HeartHandshake, Megaphone, UserRound, Newspaper, BookOpen, HandHeart } from 'lucide-react';
import { requireChurch } from '@/lib/auth';

export default async function MemberDashboard() {
  const {supabase,churchId,user,churchName,profileName,roleKey}=await requireChurch(); const now=new Date().toISOString();
  const [events,announcements,notifications,member,posts,content]=await Promise.all([
    supabase.from('events').select('id,title,description,starts_at,address,status').eq('church_id',churchId).gte('starts_at',now).order('starts_at').limit(4),
    supabase.from('announcements').select('id,title,body,published_at').eq('church_id',churchId).eq('published',true).order('published_at',{ascending:false}).limit(3),
    supabase.from('notifications').select('id,title,body,created_at,read_at').eq('church_id',churchId).eq('user_id',user.id).is('archived_at',null).order('created_at',{ascending:false}).limit(4),
    supabase.from('church_members').select('id,full_name,status,joined_at,baptism_date').eq('church_id',churchId).eq('auth_user_id',user.id).maybeSingle(),
    supabase.from('posts').select('id,title,body,post_type,published_at').eq('church_id',churchId).eq('published',true).order('published_at',{ascending:false}).limit(2),
    supabase.from('content_library').select('id,title,description,category,content_type,url,media_url').eq('church_id',churchId).eq('published',true).order('published_at',{ascending:false}).limit(3),
  ]);
  const schedules=member.data?.id ? await supabase.from('volunteer_schedules').select('id,function_name,starts_at,status,events(title)').eq('church_id',churchId).eq('member_id',member.data.id).gte('starts_at',now).order('starts_at').limit(4) : {data:[] as any[]};

  return <><header className="hero hero-member"><div><span className="eyebrow">Olá, {profileName}</span><h1>Bem-vindo à {churchName}</h1><p>Acompanhe o que está acontecendo na sua comunidade e encontre seus próximos passos.</p></div>{roleKey!=='member'&&<Link className="btn secondary-light" href="/admin">Abrir administração</Link>}</header>
  <section className="quick-grid"><div className="quick-card"><span className="quick-icon"><UserRound size={20}/></span><div><small>Seu vínculo</small><strong>{member.data?.status?String(member.data.status):'Comunidade'}</strong></div></div><div className="quick-card"><span className="quick-icon"><CalendarDays size={20}/></span><div><small>Próximos eventos</small><strong>{events.data?.length||0}</strong></div></div><Link className="quick-card" href="/feed"><span className="quick-icon"><Newspaper size={20}/></span><div><small>Mural</small><strong>{posts.data?.length||0} novidades</strong></div></Link><Link className="quick-card" href="/content"><span className="quick-icon"><BookOpen size={20}/></span><div><small>Conteúdos</small><strong>{content.data?.length||0} recentes</strong></div></Link></section>
  <section className="content-grid"><div className="stack">
    <section className="card"><div className="section-head"><div><span className="eyebrow">Agenda</span><h2>Próximos eventos</h2></div><Link href="/events">Ver todos</Link></div><div className="event-list">{events.data?.length?events.data.map(e=><article className="event-item" key={e.id}><div className="date-box"><strong>{new Date(e.starts_at).getDate()}</strong><span>{new Date(e.starts_at).toLocaleDateString('pt-BR',{month:'short'}).replace('.','')}</span></div><div><h3><Link className="table-link" href={'/events/'+e.id}>{e.title}</Link></h3><p>{new Date(e.starts_at).toLocaleString('pt-BR',{dateStyle:'medium',timeStyle:'short'})}{e.address?' • '+e.address:''}</p></div></article>):<div className="empty compact">Nenhum evento futuro publicado.</div>}</div></section>
    <section className="card"><div className="section-head"><div><span className="eyebrow">Comunidade</span><h2>Últimas do mural</h2></div><Link href="/feed">Abrir mural</Link></div><div className="announcement-list">{posts.data?.length?posts.data.map(item=><article className="announcement" key={item.id}><h3>{item.title||'Publicação'}</h3><p>{item.body}</p><small>{new Date(item.published_at).toLocaleDateString('pt-BR')}</small></article>):announcements.data?.length?announcements.data.map(item=><article className="announcement" key={item.id}><h3>{item.title}</h3><p>{item.body}</p><small>{new Date(item.published_at).toLocaleDateString('pt-BR')}</small></article>):<div className="empty compact">Nenhuma novidade publicada.</div>}</div></section>
    <section className="card"><div className="section-head"><div><span className="eyebrow">Para você</span><h2>Conteúdos recentes</h2></div><Link href="/content">Ver biblioteca</Link></div><div className="content-mini-grid">{content.data?.length?content.data.map(item=><article className="content-mini" key={item.id}><span className="metric-icon"><BookOpen size={17}/></span><div><strong>{item.title}</strong><span>{item.category||item.content_type}</span></div></article>):<div className="empty compact">Nenhum conteúdo recente.</div>}</div></section>
  </div><aside className="stack">
    <section className="card accent-card"><span className="eyebrow">Cuidado pastoral</span><h2>Como podemos orar por você?</h2><p>Envie um pedido de oração. Ele fica vinculado à sua conta e pode ser tratado com privacidade.</p><form action="/api/prayer" method="post" className="form compact-form"><input name="title" placeholder="Assunto do pedido" required/><textarea name="body" rows={4} placeholder="Conte o que está no seu coração" required/><button className="btn" type="submit">Enviar pedido</button></form></section>
    {schedules.data?.length?<section className="card"><div className="section-head"><h2>Minhas escalas</h2><span className="metric-icon"><HandHeart size={17}/></span></div>{schedules.data.map((s:any)=><div className="mini-item" key={s.id}><strong>{s.function_name} • {s.events?.title||'Evento'}</strong><span>{new Date(s.starts_at).toLocaleString('pt-BR')} • {s.status}</span></div>)}</section>:null}
    <section className="card"><div className="section-head"><h2>Notificações</h2><Link href="/notifications">Ver todas</Link></div><div className="mini-list">{notifications.data?.length?notifications.data.map(item=><div className="mini-item" key={item.id}><strong>{item.title}</strong><span>{item.body||'Nova atualização disponível.'}</span></div>):<div className="empty compact">Você está em dia.</div>}</div></section>
  </aside></section></>;
}
