import { Baby } from 'lucide-react';
import { requireChurch } from '@/lib/auth';
import { createChild } from './actions';

export default async function KidsPage() {
  const { supabase, churchId } = await requireChurch();
  const [{ data: children }, { data: checkins }] = await Promise.all([
    supabase.from('kids_children').select('id,full_name,birth_date,guardian_name,guardian_phone,allergies').eq('church_id', churchId).eq('active', true).order('full_name'),
    supabase.from('kids_checkins').select('id,security_code,checked_in_at,checked_out_at,kids_children(full_name)').eq('church_id', churchId).order('checked_in_at', { ascending: false }).limit(20),
  ]);

  return <><header className="topbar"><div className="title"><span className="eyebrow">Segurança infantil</span><h1>Kids</h1><p>Cadastre crianças e acompanhe os check-ins da operação infantil.</p></div></header><section className="content-grid admin-grid"><div className="stack"><section className="card"><div className="section-head"><h2>Crianças</h2><span className="badge">{children?.length||0} ativas</span></div>{children?.length?<div className="table-wrap"><table className="table"><thead><tr><th>Nome</th><th>Nascimento</th><th>Responsável</th><th>Telefone</th><th>Alergias</th></tr></thead><tbody>{children.map(child=><tr key={child.id}><td><strong>{child.full_name}</strong></td><td>{child.birth_date?new Date(child.birth_date+'T12:00:00').toLocaleDateString('pt-BR'):'—'}</td><td>{child.guardian_name}</td><td>{child.guardian_phone||'—'}</td><td>{child.allergies||'—'}</td></tr>)}</tbody></table></div>:<div className="empty">Nenhuma criança cadastrada ainda.</div>}</section><section className="card"><h2>Check-ins recentes</h2><div className="mini-list">{checkins?.length?checkins.map((item:any)=><div className="mini-item" key={item.id}><strong>{item.kids_children?.full_name||'Criança'}</strong><span>Código {item.security_code} • {new Date(item.checked_in_at).toLocaleString('pt-BR')}</span></div>):<div className="empty compact">Nenhum check-in recente.</div>}</div></section></div><aside className="card sticky-card"><div className="section-head"><h2>Nova criança</h2><span className="metric-icon"><Baby size={18}/></span></div><form action={createChild} className="form"><div className="field"><label htmlFor="fullName">Nome</label><input id="fullName" name="fullName" required/></div><div className="field"><label htmlFor="birthDate">Nascimento</label><input id="birthDate" name="birthDate" type="date"/></div><div className="field"><label htmlFor="guardianName">Responsável</label><input id="guardianName" name="guardianName" required/></div><div className="field"><label htmlFor="guardianPhone">Telefone</label><input id="guardianPhone" name="guardianPhone"/></div><div className="field"><label htmlFor="allergies">Alergias/observações</label><textarea id="allergies" name="allergies" rows={3}/></div><button className="btn" type="submit">Cadastrar criança</button></form></aside></section></>;
}
