import { Baby } from 'lucide-react';
import { requireChurch } from '@/lib/auth';
import { addGuardian, checkInChild, checkOutChild, createChild } from './actions';

export default async function KidsPage({searchParams}:{searchParams:Promise<{error?:string;code?:string}>}){
 const qs=await searchParams;const {supabase,churchId}=await requireChurch();
 const [{data:children},{data:checkins},{data:guardians}]=await Promise.all([
  supabase.from('kids_children').select('*').eq('church_id',churchId).eq('active',true).order('full_name'),
  supabase.from('kids_checkins').select('id,child_id,security_code,room,teacher_name,checked_in_at,checked_out_at,kids_children(full_name)').eq('church_id',churchId).order('checked_in_at',{ascending:false}).limit(30),
  supabase.from('kids_guardians').select('*').eq('church_id',churchId).order('full_name'),
 ]);
 const active=(checkins||[]).filter(c=>!c.checked_out_at);
 return <><header className="topbar"><div className="title"><span className="eyebrow">Segurança infantil</span><h1>Kids</h1><p>Crianças, responsáveis autorizados e controle seguro de entrada e saída.</p></div></header>{qs.error&&<p className="alert">{qs.error}</p>}{qs.code&&<p className="success-alert">Check-in realizado. Código de segurança: <strong>{qs.code}</strong></p>}
 <section className="grid kpis kids-kpis"><div className="card kpi"><span className="muted">Crianças cadastradas</span><strong>{children?.length||0}</strong></div><div className="card kpi"><span className="muted">Dentro agora</span><strong>{active.length}</strong></div><div className="card kpi"><span className="muted">Responsáveis autorizados</span><strong>{(guardians||[]).filter(g=>g.can_pickup).length}</strong></div></section>
 <section className="content-grid admin-grid"><div className="stack">
  <section className="card"><div className="section-head"><h2>Crianças</h2><span className="badge">{children?.length||0} ativas</span></div>{children?.length?<div className="table-wrap"><table className="table"><thead><tr><th>Nome</th><th>Responsável</th><th>Telefone</th><th>Alergias</th><th>Restrições</th><th>Ação</th></tr></thead><tbody>{children.map(child=>{const checkin=checkInChild.bind(null,child.id);return <tr key={child.id}><td><strong>{child.full_name}</strong></td><td>{child.guardian_name}</td><td>{child.guardian_phone||'—'}</td><td>{child.allergies||'—'}</td><td>{child.restrictions||'—'}</td><td><form action={checkin} className="inline-form"><input name="room" placeholder="Sala"/><input name="teacher_name" placeholder="Professor"/><button type="submit">Check-in</button></form></td></tr>})}</tbody></table></div>:<div className="empty">Nenhuma criança cadastrada ainda.</div>}</section>
  <section className="card"><h2>Check-ins ativos</h2>{active.length?active.map((item:any)=>{const checkout=checkOutChild.bind(null,item.id);const childGuardians=(guardians||[]).filter(g=>g.child_id===item.child_id&&g.can_pickup);return <article className="checkout-card" key={item.id}><div><strong>{item.kids_children?.full_name||'Criança'}</strong><span>Entrada {new Date(item.checked_in_at).toLocaleString('pt-BR')} • Sala {item.room||'—'} • Prof. {item.teacher_name||'—'}</span></div><form action={checkout} className="checkout-form"><select name="guardian_id" required><option value="">Responsável</option>{childGuardians.map(g=><option value={g.id} key={g.id}>{g.full_name}</option>)}</select><input name="security_code" inputMode="numeric" placeholder="Código de segurança" required/><button className="btn secondary" type="submit">Checkout</button></form></article>}):<div className="empty compact">Nenhuma criança em atendimento agora.</div>}</section>
  <section className="card"><h2>Responsáveis</h2>{children?.map(child=>{const add=addGuardian.bind(null,child.id);const gs=(guardians||[]).filter(g=>g.child_id===child.id);return <div className="guardian-block" key={child.id}><strong>{child.full_name}</strong><div className="guardian-list">{gs.map(g=><span className="badge" key={g.id}>{g.full_name} • {g.can_pickup?'autorizado':'sem retirada'}</span>)}</div><form action={add} className="inline-add"><input name="full_name" placeholder="Novo responsável" required/><input name="phone" placeholder="Telefone"/><input name="relationship" placeholder="Parentesco"/><label><input name="can_pickup" type="checkbox" defaultChecked/> Pode retirar</label><button type="submit">Adicionar</button></form></div>})}</section>
 </div><aside className="card sticky-card"><div className="section-head"><h2>Nova criança</h2><span className="metric-icon"><Baby size={18}/></span></div><form action={createChild} className="form"><div className="field"><label>Nome</label><input name="fullName" required/></div><div className="field"><label>Nascimento</label><input name="birthDate" type="date"/></div><div className="field"><label>Responsável principal</label><input name="guardianName" required/></div><div className="field"><label>Telefone</label><input name="guardianPhone"/></div><div className="field"><label>Alergias</label><textarea name="allergies" rows={2}/></div><div className="field"><label>Medicamentos</label><textarea name="medications" rows={2}/></div><div className="field"><label>Restrições</label><textarea name="restrictions" rows={2}/></div><button className="btn" type="submit">Cadastrar criança</button></form></aside></section></>;
}
